[package]

name = "snake_game"
version = "0.1.0"
authors = ["CyberSander"]

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.37.0"
pistoncore-glutin_window = "0.66.0"
piston2d-opengl_graphics = "0.74.0"
rand = "0.7.3"
rodio = "0.11.0"